"""Shared constants for HAMMER."""

PHASE_BASELINE = "baseline"
PHASE_MUTATION = "mutation"
PHASE_IDEMPOTENCE = "idempotence"

ALL_PHASES = [PHASE_BASELINE, PHASE_MUTATION, PHASE_IDEMPOTENCE]
OVERLAY_PHASES = [PHASE_BASELINE, PHASE_MUTATION]
